// protoc --go_out=. --go-grpc_out=. cmd/proto/wallet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cmd/proto/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *WalletData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateWalletResponse) GetData() *WalletData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WalletData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletData) Reset() {
	*x = WalletData{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletData) ProtoMessage() {}

func (x *WalletData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletData.ProtoReflect.Descriptor instead.
func (*WalletData) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_cmd_proto_wallet_proto protoreflect.FileDescriptor

const file_cmd_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16cmd/proto/wallet.proto\x12\x06wallet\".\n" +
	"\x13CreateWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"X\n" +
	"\x14CreateWalletResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.wallet.WalletDataR\x04data\"?\n" +
	"\n" +
	"WalletData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance2S\n" +
	"\x06Wallet\x12I\n" +
	"\fCreateWallet\x12\x1b.wallet.CreateWalletRequest\x1a\x1c.wallet.CreateWalletResponseB\fZ\n" +
	"cmd/walletb\x06proto3"

var (
	file_cmd_proto_wallet_proto_rawDescOnce sync.Once
	file_cmd_proto_wallet_proto_rawDescData []byte
)

func file_cmd_proto_wallet_proto_rawDescGZIP() []byte {
	file_cmd_proto_wallet_proto_rawDescOnce.Do(func() {
		file_cmd_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_wallet_proto_rawDesc), len(file_cmd_proto_wallet_proto_rawDesc)))
	})
	return file_cmd_proto_wallet_proto_rawDescData
}

var file_cmd_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_proto_wallet_proto_goTypes = []any{
	(*CreateWalletRequest)(nil),  // 0: wallet.CreateWalletRequest
	(*CreateWalletResponse)(nil), // 1: wallet.CreateWalletResponse
	(*WalletData)(nil),           // 2: wallet.WalletData
}
var file_cmd_proto_wallet_proto_depIdxs = []int32{
	2, // 0: wallet.CreateWalletResponse.data:type_name -> wallet.WalletData
	0, // 1: wallet.Wallet.CreateWallet:input_type -> wallet.CreateWalletRequest
	1, // 2: wallet.Wallet.CreateWallet:output_type -> wallet.CreateWalletResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_proto_wallet_proto_init() }
func file_cmd_proto_wallet_proto_init() {
	if File_cmd_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_wallet_proto_rawDesc), len(file_cmd_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_wallet_proto_goTypes,
		DependencyIndexes: file_cmd_proto_wallet_proto_depIdxs,
		MessageInfos:      file_cmd_proto_wallet_proto_msgTypes,
	}.Build()
	File_cmd_proto_wallet_proto = out.File
	file_cmd_proto_wallet_proto_goTypes = nil
	file_cmd_proto_wallet_proto_depIdxs = nil
}
